### PR TITLE
add Series 5 data

### PR DESCRIPTION
**Pull request by oooldCaption**
add Series 5 data

### CODE REVIEW

**Comment by posva** [comment]
Thanks! Tested Marlo with a writable NFC card and it works perfectly!

**Comment by katubug** [comment]
Tested Sasha & Ione, also worked!

**Comment by dspec13** [comment]
Tested Raymond. Works like a charm

**Comment by rachaelesler** [comment]
Tested Reneigh, works perfect!

**Comment by tinylibrary** [comment]
How can I add this new info to the Amiibot app? Are there new keys I can
download?

**Comment by oooldCaption** [comment]
> 

I used locked-secret.bin and unfixed-info.bin. it's this file can't work on u device?

**Comment by miffycs** [comment]
Hey @oooldCaption, appreciate the PR 🙌

Per your README these files were ripped from the game, and there might be subtle differences than the once ripped directly from the cards. I'll do some testing this weekend before I merge, leaving this open for anyone to test for now.

**Comment by miffycs** [comment]
Found actual amiibo `.bin` files ripped from amiibo cards. Prefer to add files from the cards rather than from game data. Closing this PR.

**Pull request closed without merging**
